/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.CacControllerKhac;
import CustomTables.CustomTable_DanhSachBaiKiemTra_Diem;
import Models.CT_SV_BKT;
import Models.SinhVien;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonan
 */
public class MainSinhVien extends javax.swing.JFrame {

    //Connection connection = ConnectToSQLServer.ketNoiCSDL();
    String tenDangNhap;
    SinhVien sinhVien = new SinhVien();

    ArrayList<CT_SV_BKT> danhSachChiTietBaiKiemTra = new ArrayList<>();
    int dongChon_ChiTietBaiKiemTra = -1;

    /**
     * Creates new form MainSinhVienF
     */
    public MainSinhVien() {
        initComponents();
    }

    public MainSinhVien(String tenDangNhap) {
        initComponents();
        this.tenDangNhap = tenDangNhap;
        layThongTinSinhVien();
        hienThi_BangDanhSachChiTietBaiKiemTra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachChiTietBaiKiemTra = new javax.swing.JTable();
        jButton_LamBai = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(705, 440));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH BÀI KIỂM TRA");

        jTable_DanhSachChiTietBaiKiemTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_DanhSachChiTietBaiKiemTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhSachChiTietBaiKiemTraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DanhSachChiTietBaiKiemTra);

        jButton_LamBai.setText("Làm bài");
        jButton_LamBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamBaiActionPerformed(evt);
            }
        });

        jMenu1.setText("Lựa chọn");

        jMenuItem1.setText("Thông tin về người sử dụng");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Thông tin về phần mềm");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Đăng xuất");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_LamBai)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton_LamBai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_DanhSachChiTietBaiKiemTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachChiTietBaiKiemTraMouseClicked
        // TODO add your handling code here:
        dongChon_ChiTietBaiKiemTra = jTable_DanhSachChiTietBaiKiemTra.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_jTable_DanhSachChiTietBaiKiemTraMouseClicked

    private void jButton_LamBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamBaiActionPerformed
        // TODO add your handling code here:
        if (dongChon_ChiTietBaiKiemTra < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn bài kiểm tra nào");
        }
        CT_SV_BKT baiKiemTra = danhSachChiTietBaiKiemTra.get(dongChon_ChiTietBaiKiemTra);

        String han = baiKiemTra.getBaiKiemTra().getHanNop();
        LocalDateTime bayGio = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        String bayGio_ = bayGio.format(myFormatObj);

        if (baiKiemTra.getTrangThai().equals("Hoàn thành")) {
            JOptionPane.showMessageDialog(null, "Bạn đã làm bài kiểm tra này rồi");
        } else if (bayGio_.compareTo(han) > 0) {
            JOptionPane.showMessageDialog(null, "Hạn làm: " + han + "\nĐã hết hạn làm bài");
        } else {
            new LamBaiKiemTraUI(danhSachChiTietBaiKiemTra.get(dongChon_ChiTietBaiKiemTra).getBaiKiemTra().getMaBKT(),
                    sinhVien.getMaSV()).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton_LamBaiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String s = "Mã sinh viên: " + sinhVien.getMaSV()
                + "\nTên sinh viên: " + sinhVien.getTenSV()
                + "\nLớp :" + sinhVien.getLop().getTenLop()
                + "\nTên tài khoản : "+ sinhVien.getTaiKhoan().getTenDangNhap();
        JOptionPane.showMessageDialog(null, s);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String s = "Phần mềm được thực hiện bởi nhóm 3"
                + "\n Thành viên:"
                + "\n -Đào Tuấn Cường"
                + "\n -Vương Tá Cường"
                + "\n -Mạc Văn Cường"
                + "\n -Ngô Văn Đang"
                + "\n -Lê Huỳnh Đức";
        JOptionPane.showMessageDialog(null, s);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        Object[] options = {"Có", "Không"};
        //Check = 0: co 1: khong
        int check = JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn đăng xuất ?", "Thông Báo",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, options, options[0]);

        if (check == 0) {
            new DangNhapUI().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSinhVien("Sinh vien 1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LamBai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DanhSachChiTietBaiKiemTra;
    // End of variables declaration//GEN-END:variables

    private void layThongTinSinhVien() {
        sinhVien = CacControllerKhac.layThongTinSinhVien(tenDangNhap);
    }

    private void hienThi_BangDanhSachChiTietBaiKiemTra() {
        danhSachChiTietBaiKiemTra = CacControllerKhac.layDanhSachBaiKiemTra_Lop(sinhVien.getMaSV(), sinhVien.getLop().getMaLop());

        jTable_DanhSachChiTietBaiKiemTra.setModel(new CustomTable_DanhSachBaiKiemTra_Diem(danhSachChiTietBaiKiemTra));
    }
}
