/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.SuaBaiKiemTraController;
import Models.BaiKiemTra;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonan
 */
public class SuaBaiKiemTraUI extends javax.swing.JFrame {
    //Connection connection = ConnectToSQLServer.ketNoiCSDL();
    
    String maBKT;
    BaiKiemTra baiKiemTra = new BaiKiemTra();
    /**
     * Creates new form SuaBaiKiemTraF
     */
    public SuaBaiKiemTraUI() {
        initComponents();
    }
    
    public SuaBaiKiemTraUI(String maBKT) {
        initComponents();
        txtMa.setEnabled(false);
        this.maBKT = maBKT;
        
        loadDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtHan = new javax.swing.JTextField();
        JButton_CapNhat = new javax.swing.JButton();
        jSpinner_ThoiGianLam = new javax.swing.JSpinner();
        jButton_TroLai = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SỬA BÀI KIỂM TRA");

        jLabel2.setText("Mã đề :");

        jLabel3.setText("Tên đề :");

        jLabel5.setText("Thời gian làm :");

        jLabel7.setText("Hạn nộp :");

        txtHan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHanFocusLost(evt);
            }
        });

        JButton_CapNhat.setText("Cập nhật");
        JButton_CapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_CapNhatMouseClicked(evt);
            }
        });

        jSpinner_ThoiGianLam.setModel(new javax.swing.SpinnerNumberModel(45, 1, 90, 1));

        jButton_TroLai.setText("Trở lại");
        jButton_TroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(JButton_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jButton_TroLai))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinner_ThoiGianLam, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addComponent(txtMa)
                            .addComponent(txtHan))))
                .addGap(72, 72, 72))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_ThoiGianLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_CapNhat)
                    .addComponent(jButton_TroLai))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_CapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_CapNhatMouseClicked
        String tenBKT = txtTen.getText();
        int thoiGianLam = Integer.parseInt(jSpinner_ThoiGianLam.getValue().toString());
        String hanNop = txtHan.getText();
        
        if(SuaBaiKiemTraController.capNhatBaiKiemTra(maBKT, tenBKT, thoiGianLam, hanNop))
        {
            JOptionPane.showMessageDialog(null, "Cập nhật bài kiểm tra thành công !!!");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Cập nhật bài kiểm tra thất bại !!!");
        }
        
        new MainMenuGiangVien(MainMenuGiangVien.giangVien.getTaiKhoan().getTenDangNhap()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JButton_CapNhatMouseClicked

    private void jButton_TroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroLaiActionPerformed
        // TODO add your handling code here:
        new MainMenuGiangVien(MainMenuGiangVien.giangVien.getTaiKhoan().getTenDangNhap()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_TroLaiActionPerformed

    private void txtHanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHanFocusLost
        // TODO add your handling code here:
        if(txtHan.getText().equals(""))
        {
            txtHan.setText("Năm-Tháng-Ngày Giờ:Phút");
            txtHan.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtHanFocusLost

    private void txtHanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHanFocusGained
        // TODO add your handling code here:
        if(txtHan.getText().equals("Năm-Tháng-Ngày Giờ:Phút"))
        {
            txtHan.setText("");
            txtHan.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtHanFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaBaiKiemTraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaBaiKiemTraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaBaiKiemTraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaBaiKiemTraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaBaiKiemTraUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_CapNhat;
    private javax.swing.JButton jButton_TroLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_ThoiGianLam;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHan;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

    private void loadDuLieu() {
        baiKiemTra = SuaBaiKiemTraController.layThongTinBaiKiemTra(maBKT);
        
        txtMa.setText(baiKiemTra.getMaBKT());
        txtTen.setText(baiKiemTra.getTenBKT());
        jSpinner_ThoiGianLam.setValue(baiKiemTra.getThoiGianLam());
        txtHan.setText(baiKiemTra.getHanNop());
    }
}
