/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import Controllers.SuaDiemController;
import Models.CT_SV_BKT;
import CustomTables.CustomTable_DanhSachChiTietBaiKiemTra;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * @author Jonan
 */
public class ChiTietBaiKiemTraForm extends javax.swing.JFrame {
    //Connection connection = ConnectToSQLServer.ketNoiCSDL();
    
    String maBKT;
    
    ArrayList<CT_SV_BKT> danhSachChiTietBaiKiemTra = new ArrayList<>();
    /**
     * Creates new form ChiTietBaiKiemTraForm
     */
    public ChiTietBaiKiemTraForm() {
        initComponents();
        //loadDataTable_BangChiTietBaiKiemTra();
    }

    ChiTietBaiKiemTraForm(String maBKT) {
        initComponents();
        this.maBKT = maBKT;
        hienThi_BangChiTietBaiKiemTra(maBKT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ChiTietBaiKiemTra = new javax.swing.JLabel();
        jButton_CapNhat = new javax.swing.JButton();
        jButton_TroLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ChiTietBaiKiemTra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(705, 440));

        jLabel_ChiTietBaiKiemTra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ChiTietBaiKiemTra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ChiTietBaiKiemTra.setText("Chi tiet bai kiem tra");

        jButton_CapNhat.setText("Cập nhật");
        jButton_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CapNhatActionPerformed(evt);
            }
        });

        jButton_TroLai.setText("Trở lại");
        jButton_TroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroLaiActionPerformed(evt);
            }
        });

        jTable_ChiTietBaiKiemTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_ChiTietBaiKiemTra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jButton_CapNhat)
                .addGap(40, 40, 40)
                .addComponent(jButton_TroLai)
                .addContainerGap(62, Short.MAX_VALUE))
            .addComponent(jLabel_ChiTietBaiKiemTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ChiTietBaiKiemTra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CapNhat)
                    .addComponent(jButton_TroLai))
                .addGap(44, 44, 44))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CapNhatActionPerformed
        // TODO add your handling code here:
        //thong bao chac chan muon cap nhat
        Object[] options = {"Có", "Không"};
        //Check = 0: co 1: khong
        int check = JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn cập nhật thông tin?", "Thông Báo",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, options, options[0]);
        //check xem co muon cap nhat khong
        //1 = khong hien thi lai bang cu 
        if (check == 1) {
            
            hienThi_BangChiTietBaiKiemTra(maBKT);
            return;
        }
        
        //0: co cap nhat lại co so du lieu
        int row = jTable_ChiTietBaiKiemTra.getRowCount();
        for(int i = 0; i< row; i++)
        {
            SuaDiemController.capNhatDiem(jTable_ChiTietBaiKiemTra.getValueAt(i, 0).toString(), 
                    maBKT, (float)jTable_ChiTietBaiKiemTra.getValueAt(i, 2));

        }
        //dua ra thong bao
        JOptionPane.showMessageDialog(null, "Cập nhật bài kiểm tra thành công");
    }//GEN-LAST:event_jButton_CapNhatActionPerformed
    private void jButton_TroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroLaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_TroLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietBaiKiemTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietBaiKiemTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietBaiKiemTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietBaiKiemTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietBaiKiemTraForm("BKT1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CapNhat;
    private javax.swing.JButton jButton_TroLai;
    private javax.swing.JLabel jLabel_ChiTietBaiKiemTra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ChiTietBaiKiemTra;
    // End of variables declaration//GEN-END:variables

//    private void hienThi_BangChiTietBaiKiemTra() {
//       jTable_ChiTietBaiKiemTra.setModel(new CustomTable_DanhSachChiTietBaiKiemTra(danhSachChiTietBaiKiemTra));
//    }

    private void hienThi_BangChiTietBaiKiemTra(String maBKT) {
        //lay du lieu tu database
        danhSachChiTietBaiKiemTra = SuaDiemController.layChiTietBaiKiemTra(maBKT);
        //sua tieu de bang
        String tieuDeBang = "CHI TIẾT BÀI KIỂM TRA " + maBKT;
        jLabel_ChiTietBaiKiemTra.setText(tieuDeBang);
        
        jTable_ChiTietBaiKiemTra.setModel(new CustomTable_DanhSachChiTietBaiKiemTra(danhSachChiTietBaiKiemTra));
    }

}
