/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.CreateExcel;
import Controllers.LayDiemController;
import Models.BaiKiemTra;
import CustomTables.CustomTable_DanhSachBaiKiemTra;
import Models.CT_SV_BKT;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author Jonan
 */
public class DanhSachBaiKiemForm extends javax.swing.JFrame {

    //Connection connection = ConnectToSQLServer.ketNoiCSDL();

    ArrayList<BaiKiemTra> danhSachBaiKiemTra = new ArrayList<>();
    int dongChon_BaiKiemTra = -1;
    
    ArrayList<CT_SV_BKT> danhSachDiem = new ArrayList<>();

    /**
     * Creates new form DanhSachBaiKiemTraForm
     */

    public DanhSachBaiKiemForm() {
        initComponents();
    }

    public DanhSachBaiKiemForm(String maLop) {
        initComponents();
        hienThi_BangDanhSachBaiKiemTra(maLop);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachBaiKiemTra = new javax.swing.JTable();
        jButton_TroLai1 = new javax.swing.JButton();
        jButton_LayDiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(705, 440));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH BÀI KIỂM TRA");

        jTable_DanhSachBaiKiemTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_DanhSachBaiKiemTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhSachBaiKiemTraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DanhSachBaiKiemTra);

        jButton_TroLai1.setText("Trở lại");
        jButton_TroLai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroLai1ActionPerformed(evt);
            }
        });

        jButton_LayDiem.setText("Lấy điểm");
        jButton_LayDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LayDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_LayDiem)
                        .addGap(31, 31, 31)
                        .addComponent(jButton_TroLai1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_LayDiem)
                    .addComponent(jButton_TroLai1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_DanhSachBaiKiemTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachBaiKiemTraMouseClicked
        // TODO add your handling code here:
        dongChon_BaiKiemTra = jTable_DanhSachBaiKiemTra.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            new ChiTietBaiKiemTraForm(danhSachBaiKiemTra.get(dongChon_BaiKiemTra).getMaBKT()).setVisible(true);
//            this.dispose();
        }

    }//GEN-LAST:event_jTable_DanhSachBaiKiemTraMouseClicked

    private void jButton_TroLai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroLai1ActionPerformed
        // TODO add your handling code here:
        new MainMenuGiangVien(MainMenuGiangVien.giangVien.getTaiKhoan().getTenDangNhap()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_TroLai1ActionPerformed

    private void jButton_LayDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LayDiemActionPerformed
        // TODO add your handling code here:
        if (dongChon_BaiKiemTra < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào", "Thông báo", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        String maBKT = jTable_DanhSachBaiKiemTra.getValueAt(dongChon_BaiKiemTra, 0).toString();
        
        ArrayList<CT_SV_BKT> danhSachDiem = LayDiemController.layChiTietBaiKiemTra(maBKT);
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Lưu file");
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Excel (*.xls)", "xls"));

        int userSelection = fileChooser.showSaveDialog(this);
        System.out.println("getSelectedFile() : " + fileChooser.getSelectedFile());
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            CreateExcel file = new CreateExcel();
            try {
                String localPathOfFile = fileChooser.getSelectedFile().toString() + ".xls";
                file.TaoFileDiem(danhSachDiem, localPathOfFile);
                JOptionPane.showMessageDialog(null, "Tạo file thành công !");
            } catch (IOException ex) {
                Logger.getLogger(DanhSachBaiKiemForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
        dongChon_BaiKiemTra = -1;
    }//GEN-LAST:event_jButton_LayDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachBaiKiemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachBaiKiemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachBaiKiemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachBaiKiemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSachBaiKiemForm("L1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LayDiem;
    private javax.swing.JButton jButton_TroLai1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DanhSachBaiKiemTra;
    // End of variables declaration//GEN-END:variables


    private void hienThi_BangDanhSachBaiKiemTra(String maLop) {
        danhSachBaiKiemTra.clear();
        //lay du lieu tu database
        danhSachBaiKiemTra = LayDiemController.layDanhSachBaiKiemTra(maLop);

        jTable_DanhSachBaiKiemTra.setModel(new CustomTable_DanhSachBaiKiemTra(danhSachBaiKiemTra));
    }

}
