/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.CacControllerKhac;
import Controllers.XoaBaiKiemTraController;
import Controllers.XoaLopController;
import Models.BaiKiemTra;
import CustomTables.CustomTable_DanhSachBaiKiemTra;
import CustomTables.CustomTable_DanhSachLop;
import Models.GiangVien;
import Models.Lop;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonan
 */
public class MainMenuGiangVien extends javax.swing.JFrame {

    //Connection connection = ConnectToSQLServer.ketNoiCSDL();
    static GiangVien giangVien = new GiangVien();

    ArrayList<Lop> danhSachLop = new ArrayList<>();
    int dongChon_Lop = -1;
    ArrayList<BaiKiemTra> danhSachBaiKiemTra = new ArrayList<>();
    int dongChon_BaiKiemTra = -1;

    /**
     * Creates new form MainMenuGiangVien
     */
    public MainMenuGiangVien() {
        initComponents();
//        this.setLocationRelativeTo(null);  // *** this will center your app ***

        hienThi_BangDanhSachLop();
        hienThi_BangDanhSachBaiKiemTra();
    }

    public MainMenuGiangVien(String tenDN) {
        initComponents();

        layThongTinGiangVien(tenDN);

        hienThi_BangDanhSachLop();
        hienThi_BangDanhSachBaiKiemTra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_QuanLyBaiKiemTra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_DanhSachBaiKiemTra = new javax.swing.JTable();
        btnTao = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        JButton_XoaBaiKiemTra = new javax.swing.JButton();
        jPanel_QuanLyLop = new javax.swing.JPanel();
        jLabel_DanhSachLop = new javax.swing.JLabel();
        jButton_XoaLop = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_DanhSachLop = new javax.swing.JTable();
        jButton_TaoLop = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(705, 440));

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ BÀI KIỂM TRA");

        jTable_DanhSachBaiKiemTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_DanhSachBaiKiemTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhSachBaiKiemTraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_DanhSachBaiKiemTra);

        btnTao.setText("Tạo ");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        JButton_XoaBaiKiemTra.setText("Xóa");
        JButton_XoaBaiKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_XoaBaiKiemTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_QuanLyBaiKiemTraLayout = new javax.swing.GroupLayout(jPanel_QuanLyBaiKiemTra);
        jPanel_QuanLyBaiKiemTra.setLayout(jPanel_QuanLyBaiKiemTraLayout);
        jPanel_QuanLyBaiKiemTraLayout.setHorizontalGroup(
            jPanel_QuanLyBaiKiemTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuanLyBaiKiemTraLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnTao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(JButton_XoaBaiKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_QuanLyBaiKiemTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel_QuanLyBaiKiemTraLayout.setVerticalGroup(
            jPanel_QuanLyBaiKiemTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuanLyBaiKiemTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel_QuanLyBaiKiemTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTao)
                    .addComponent(btnSua)
                    .addComponent(JButton_XoaBaiKiemTra))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý bài kiểm tra", jPanel_QuanLyBaiKiemTra);

        jLabel_DanhSachLop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_DanhSachLop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_DanhSachLop.setText("DANH SÁCH LỚP");

        jButton_XoaLop.setText("Xoá");
        jButton_XoaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaLopActionPerformed(evt);
            }
        });

        jTable_DanhSachLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_DanhSachLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhSachLopMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_DanhSachLop);

        jButton_TaoLop.setText("Tạo");
        jButton_TaoLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TaoLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_QuanLyLopLayout = new javax.swing.GroupLayout(jPanel_QuanLyLop);
        jPanel_QuanLyLop.setLayout(jPanel_QuanLyLopLayout);
        jPanel_QuanLyLopLayout.setHorizontalGroup(
            jPanel_QuanLyLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuanLyLopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addComponent(jLabel_DanhSachLop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_QuanLyLopLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButton_TaoLop)
                .addGap(134, 134, 134)
                .addComponent(jButton_XoaLop)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel_QuanLyLopLayout.setVerticalGroup(
            jPanel_QuanLyLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuanLyLopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_DanhSachLop)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel_QuanLyLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_XoaLop)
                    .addComponent(jButton_TaoLop))
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Quản lý lớp", jPanel_QuanLyLop);

        jMenu1.setText("Lựa chọn");

        jMenuItem1.setText("Thông tin về người sử dụng");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Thông tin về phần mềm");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Đăng xuất");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_XoaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaLopActionPerformed
        // TODO add your handling code here:
        //check xem co dong nao duoc chon chua
        if (dongChon_Lop < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào để xóa", "Thông báo", JOptionPane.DEFAULT_OPTION);
            return;
        }
        //thong bao co muon xoa khong
        Object[] options = {"Có", "Không"};
        //Check = 0: co 1: khong
        int check = JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn xóa ?", "Thông Báo",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, options, options[0]);

        if (check == 0) {
            String maLop = jTable_DanhSachLop.getValueAt(dongChon_Lop, 0).toString();
            
            XoaLopController.xoaLop(maLop);
            //dat lai chua chon dong
            dongChon_Lop = -1;
            //hien thi lai bang
            hienThi_BangDanhSachLop();
        }
    }//GEN-LAST:event_jButton_XoaLopActionPerformed

    private void JButton_XoaBaiKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_XoaBaiKiemTraActionPerformed
        // TODO add your handling code here:
        //check dong được chọn chưa
        if (dongChon_BaiKiemTra < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào để xóa", "Thông báo", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        //thong bao hoi muon xoa hay khong
        Object[] options = {"Có", "Không"};
        //Check = 0: co 1: khong
        int check = JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn xóa ?", "Thông Báo",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, options, options[0]);

        if (check == 0) {
            //xoa trong database
            String maBKT = jTable_DanhSachBaiKiemTra.getValueAt(dongChon_BaiKiemTra, 0).toString();
            XoaBaiKiemTraController.xoaBaiKiemTra(maBKT);
            //dat lai chua chon dong nao
            dongChon_BaiKiemTra = -1;
            //hien thi lại bang
            hienThi_BangDanhSachBaiKiemTra();
        }
    }//GEN-LAST:event_JButton_XoaBaiKiemTraActionPerformed

    private void jTable_DanhSachBaiKiemTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachBaiKiemTraMouseClicked
        // TODO add your handling code here:
        dongChon_BaiKiemTra = jTable_DanhSachBaiKiemTra.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_jTable_DanhSachBaiKiemTraMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        hienThi_BangDanhSachBaiKiemTra();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTable_DanhSachLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachLopMouseClicked
        // TODO add your handling code here:
        dongChon_Lop = jTable_DanhSachLop.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            new DanhSachBaiKiemForm(danhSachLop.get(dongChon_Lop).getMaLop()).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTable_DanhSachLopMouseClicked

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
        // TODO add your handling code here:
        new TaoBaiKiemTRaUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTaoActionPerformed

    private void jButton_TaoLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TaoLopActionPerformed
        // TODO add your handling code here:
        new TaoLopUI(giangVien.getMaGV()).setVisible(true);
    }//GEN-LAST:event_jButton_TaoLopActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (dongChon_BaiKiemTra < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào !!!");
            return;
        }
        String maBKT = danhSachBaiKiemTra.get(dongChon_BaiKiemTra).getMaBKT();
        dongChon_BaiKiemTra = -1;

        new SuaBaiKiemTraUI(maBKT).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String s = "Mã giảng viên: " + giangVien.getMaGV()
        + "\nTên giảng viên: " + giangVien.getTenGV()
        + "\nTên tài khoản : "+ giangVien.getTaiKhoan().getTenDangNhap();
        JOptionPane.showMessageDialog(null, s);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String s = "Phần mềm được thực hiện bởi nhóm 3"
            + "\n Thành viên:"
            + "\n -Đào Tuấn Cường"
            + "\n -Vương Tá Cường"
            + "\n -Mạc Văn Cường"
            + "\n -Ngô Văn Đang"
            + "\n -Lê Huỳnh Đức";
        JOptionPane.showMessageDialog(null, s);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        Object[] options = {"Có", "Không"};
        //Check = 0: co 1: khong
        int check = JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn đăng xuất ?", "Thông Báo",
            JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
            null, options, options[0]);

        if (check == 0) {
            new DangNhapUI().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGiangVien("GiangVien1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_XoaBaiKiemTra;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTao;
    private javax.swing.JButton jButton_TaoLop;
    private javax.swing.JButton jButton_XoaLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_DanhSachLop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel_QuanLyBaiKiemTra;
    private javax.swing.JPanel jPanel_QuanLyLop;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_DanhSachBaiKiemTra;
    private javax.swing.JTable jTable_DanhSachLop;
    // End of variables declaration//GEN-END:variables

    private void hienThi_BangDanhSachLop() {
        danhSachLop.clear();
        //lay du lieu tu database
        capNhatSoLuongSinhVien();

        danhSachLop = XoaLopController.layDanhSachLop(giangVien);
        jTable_DanhSachLop.setModel(new CustomTable_DanhSachLop(danhSachLop));
    }

    private void hienThi_BangDanhSachBaiKiemTra() {
        danhSachBaiKiemTra.clear();
        //lay du lieu tu database
        Iterator<Lop> it = danhSachLop.iterator();
        while (it.hasNext()) {
            //lay theo tung lop
            ArrayList<BaiKiemTra> temp = XoaBaiKiemTraController.layDanhSachBaiKiemTra(it.next().getMaLop());
            //them tat ca bai kiem tra cua lop vao danh sach
            danhSachBaiKiemTra.addAll(temp);
        }
        
        jTable_DanhSachBaiKiemTra.setModel(new CustomTable_DanhSachBaiKiemTra(danhSachBaiKiemTra));
    }

    private void layThongTinGiangVien(String tenDN) {
        giangVien = CacControllerKhac.layThongTinGiangVien(tenDN);
    }

    private void capNhatSoLuongSinhVien() {
        CacControllerKhac.capNhatSoLuongSinhVien(giangVien.getMaGV());
    }
}
