/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.QLCauHoiController;
import CustomTables.CustomTable_DanhSachCauHoi;
import java.util.ArrayList;
import Models.CauHoi;
import java.util.Iterator;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class QuanLyCauHoiUI extends javax.swing.JFrame {

    //Connection connection = ConnectToSQLServer.ketNoiCSDL();
    int soCauHoi;
    int doKho;

    ArrayList<CauHoi> danhSachCauHoi = new ArrayList<>();
    int selectedRow = -1;
    //int id;
    //DefaultTableModel model;

    public QuanLyCauHoiUI() {
        initComponents();
        //setLocationRelativeTo(null);
        rdA.setActionCommand("A");
        rdB.setActionCommand("B");
        rdC.setActionCommand("C");
        rdD.setActionCommand("D");

        rdDe.setActionCommand("Dễ");
        rdKho.setActionCommand("Khó");

        hienThi_BangCauHoi_KhoDe();

        // setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    public QuanLyCauHoiUI(int soCauHoi, int doKho) {
        initComponents();
        //setLocationRelativeTo(null);
        this.soCauHoi = soCauHoi;
        this.doKho = doKho;

        rdA.setActionCommand("A");
        rdB.setActionCommand("B");
        rdC.setActionCommand("C");
        rdD.setActionCommand("D");

        rdDe.setActionCommand("Dễ");
        rdKho.setActionCommand("Khó");

        hienThi_BangCauHoi_KhoDe();

        //(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_DoKho = new javax.swing.ButtonGroup();
        buttonGroup_DapAnDung = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDS = new javax.swing.JTable();
        txtTim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        btnTao = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        brnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rdA = new javax.swing.JRadioButton();
        rdB = new javax.swing.JRadioButton();
        rdC = new javax.swing.JRadioButton();
        rdD = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtND = new javax.swing.JTextArea();
        rdDe = new javax.swing.JRadioButton();
        rdKho = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ CÂU HỎI");

        tblDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDS);

        jLabel2.setText("Nhập ID tìm kiếm :");

        btnTim.setText("Tìm kiếm");
        btnTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimMouseClicked(evt);
            }
        });

        btnTao.setText("Tạo ngẫu nhiên câu hỏi cho bài kiểm tra");
        btnTao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaoMouseClicked(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        brnXoa.setText("Xóa");
        brnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brnXoaMouseClicked(evt);
            }
        });

        btnHuy.setText("Hủy thao tác");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuayLaiMouseClicked(evt);
            }
        });

        jLabel3.setText("Nội dung : ");

        jLabel4.setText("Độ khó : ");

        jLabel5.setText("Đáp án A :");

        jLabel6.setText("Đáp án B :");

        jLabel7.setText("Đáp án C :");

        jLabel8.setText("Đáp án D :");

        jLabel9.setText("Đáp án Đúng : ");

        buttonGroup_DapAnDung.add(rdA);
        rdA.setText("A");

        buttonGroup_DapAnDung.add(rdB);
        rdB.setText("B");

        buttonGroup_DapAnDung.add(rdC);
        rdC.setText("C");

        buttonGroup_DapAnDung.add(rdD);
        rdD.setText("D");

        txtND.setColumns(20);
        txtND.setRows(5);
        jScrollPane2.setViewportView(txtND);

        buttonGroup_DoKho.add(rdDe);
        rdDe.setText("Dễ");

        buttonGroup_DoKho.add(rdKho);
        rdKho.setText("Khó");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DANH SÁCH CÂU HỎI");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("DD");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("CC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnTao, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtB)
                    .addComponent(txtD, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addGap(35, 35, 35))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(rdDe, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(rdKho, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(brnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnHuy))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton1)
                                .addGap(17, 17, 17)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(70, 70, 70))))))
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdDe)
                    .addComponent(rdKho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rdA)
                    .addComponent(rdB)
                    .addComponent(rdC)
                    .addComponent(rdD)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(brnXoa)
                    .addComponent(jLabel2)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(btnHuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTao)
                    .addComponent(btnQuayLai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        if (txtND.getText().equals("") || txtA.getText().equals("")
                || txtB.getText().equals("") || txtC.getText().equals("")
                || txtD.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền đầy đủ đáp án", "LỖI", JOptionPane.ERROR_MESSAGE);
        } else {
            String noiDung = txtND.getText();
            String dapAnA = txtA.getText();
            String dapAnB = txtB.getText();
            String dapAnC = txtC.getText();
            String dapAnD = txtD.getText();
            String doKho = buttonGroup_DoKho.getSelection().getActionCommand();
            String dapAnDung = buttonGroup_DapAnDung.getSelection().getActionCommand();

            if (QLCauHoiController.themCauHoi(noiDung, dapAnA, dapAnB, dapAnC, dapAnD, dapAnDung, doKho)) {
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại");
            }

            hienThi_BangCauHoi_KhoDe();
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        try {
            CauHoi p = danhSachCauHoi.get(selectedRow);
            int maCH = p.getMaCH();

            String noiDung = txtND.getText();
            String dapAnA = txtA.getText();
            String dapAnB = txtB.getText();
            String dapAnC = txtC.getText();
            String dapAnD = txtD.getText();
            String doKho = buttonGroup_DoKho.getSelection().getActionCommand();
            String dapAnDung = buttonGroup_DapAnDung.getSelection().getActionCommand();

            if (QLCauHoiController.suaCauHoi(maCH, noiDung, dapAnA, dapAnB, dapAnC, dapAnD, dapAnDung, doKho)) {
                JOptionPane.showMessageDialog(null, "Sửa thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
            }

            hienThi_BangCauHoi_KhoDe();
            selectedRow = -1;
            deleteText();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnTaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoMouseClicked

        ArrayList<CauHoi> de = new ArrayList<>();
        ArrayList<CauHoi> kho = new ArrayList<>();
        ArrayList<CauHoi> De = new ArrayList<>();
        ArrayList<CauHoi> Kho = new ArrayList<>();

        for (CauHoi a : danhSachCauHoi) {
            if (a.getDoKho().equals("Dễ")) {
                de.add(a);
            } else {
                kho.add(a);
            }
        }

        Random rd = new Random();
        int soCauDe = doKho * soCauHoi / 100;
        for (int i = 1; i <= soCauDe; i++) {
            int rdDe = rd.nextInt(de.size());
            CauHoi de1 = de.get(rdDe);
            De.add(de1);
            de.remove(rdDe);
        }
        for (int i = 1; i <= soCauHoi - soCauDe; i++) {
            int rdKho = rd.nextInt(kho.size());
            CauHoi kho1 = kho.get(rdKho);
            Kho.add(kho1);
            kho.remove(rdKho);
        }

        ArrayList<CauHoi> danSachCauHoi_BKT = new ArrayList<>();
        danSachCauHoi_BKT.addAll(De);
        danSachCauHoi_BKT.addAll(Kho);

        tblDS.setModel(new CustomTable_DanhSachCauHoi(danSachCauHoi_BKT));
        TaoBaiKiemTRaUI.danhSachCauHoi = danSachCauHoi_BKT;
    }//GEN-LAST:event_btnTaoMouseClicked

    private void tblDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMouseClicked
        selectedRow = tblDS.getSelectedRow();
        CauHoi p = danhSachCauHoi.get(selectedRow);
        txtND.setText(p.getNoiDung());
        txtA.setText(p.getA());
        txtB.setText(p.getB());
        txtC.setText(p.getC());
        txtD.setText(p.getD());
        if ("Dễ".equals(p.getDoKho())) {
            rdDe.setSelected(true);
        } else {
            rdKho.setSelected(true);
        }

        if (p.getDapAn().equals("A")) {
            rdA.setSelected(true);
        }
        if (p.getDapAn().equals("B")) {
            rdB.setSelected(true);
        }
        if (p.getDapAn().equals("C")) {
            rdC.setSelected(true);
        }
        if (p.getDapAn().equals("D")) {
            rdD.setSelected(true);
        }

    }//GEN-LAST:event_tblDSMouseClicked

    private void brnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brnXoaMouseClicked
        try {
            CauHoi p = danhSachCauHoi.get(selectedRow);

            if (QLCauHoiController.xoaCauHoi(p.getMaCH())) {
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                System.out.println("Xoa thanh cong");
            } else {
                System.out.println("xoa that bai");
            }
            hienThi_BangCauHoi_KhoDe();
            selectedRow = -1;
            deleteText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ban chua chon dong", "LOI", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_brnXoaMouseClicked

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        selectedRow = -1;
        tblDS.clearSelection();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void btnQuayLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuayLaiMouseClicked

        this.dispose();
    }//GEN-LAST:event_btnQuayLaiMouseClicked

    private void btnTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimMouseClicked
        try {
            int maCH = Integer.parseInt(txtTim.getText());
            ArrayList<CauHoi> listFind = new ArrayList<>();
            Iterator<CauHoi> ite = danhSachCauHoi.iterator();
            try {
                while (ite.hasNext()) {
                    CauHoi p = ite.next();
                    if (p.getMaCH() == maCH) {
                        listFind.add(p);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Khong co cau hoi", "THONG BAO", JOptionPane.ERROR_MESSAGE);
            }
            tblDS.setModel(new CustomTable_DanhSachCauHoi(listFind));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bạn nhập không đúng định dạng ID", "LỖI", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnTimMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a = jRadioButton1.isSelected() ? "De" : "Kho";
        System.out.println(a);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyCauHoiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyCauHoiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyCauHoiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyCauHoiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyCauHoiUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnXoa;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTao;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup_DapAnDung;
    private javax.swing.ButtonGroup buttonGroup_DoKho;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdA;
    private javax.swing.JRadioButton rdB;
    private javax.swing.JRadioButton rdC;
    private javax.swing.JRadioButton rdD;
    private javax.swing.JRadioButton rdDe;
    private javax.swing.JRadioButton rdKho;
    private javax.swing.JTable tblDS;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextArea txtND;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables

    private void hienThi_BangCauHoi_KhoDe() {

        danhSachCauHoi = QLCauHoiController.layKhoDe();

        tblDS.setModel(new CustomTable_DanhSachCauHoi(danhSachCauHoi));
    }

    public void deleteText() {
        String t = "";
        txtND.setText(t);
        txtA.setText(t);
        txtB.setText(t);
        txtC.setText(t);
        txtD.setText(t);
    }
}
